Repository taco-official/klkl-server, pull requests merged in 2024-07, with the labels that each got.

#2 docs(KL-17): add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📝 Docs

#3 docs(KL-25): add git commit template
  .gitmessage.txt
Labels: 📝 Docs

#4 docs(KL-54): set docker environment
  Dockerfile
  Makefile
  compose.yaml
Labels: 📝 Docs

#5 docs(KL-55): add makefile workflow
  .github/workflows/makefile.yaml
Labels: 📝 Docs

#7 feat(KL-62): connect h2 database
  src/main/java/taco/klkl/security/SecurityConfig.java
  src/main/resources/application.properties
Labels: ✨ Feature

#8 feat(KL-63): connect Swagger
  build.gradle
  src/main/java/taco/klkl/global/config/swagger/SwaggerConfig.java
  src/main/java/taco/klkl/security/SecurityConfig.java
  src/main/resources/application-h2.yaml
  src/main/resources/application-swagger.yaml
  src/main/resources/application.properties
  src/main/resources/application.yaml
Labels: ✨ Feature

#9 feat(KL-64): Global Response 세팅
  src/main/java/taco/klkl/global/error/ErrorResponse.java
  src/main/java/taco/klkl/global/error/GlobalExceptionHandler.java
  src/main/java/taco/klkl/global/error/exception/CustomException.java
  src/main/java/taco/klkl/global/error/exception/ErrorCode.java
  src/main/java/taco/klkl/global/response/GlobalResponse.java
  src/main/java/taco/klkl/global/response/GlobalResponseAdvice.java
  src/test/java/taco/klkl/global/error/GlobalExceptionHandlerTest.java
  src/test/java/taco/klkl/global/response/GlobalResponseAdviceTest.java
Labels: ✅ Test, ✨ Feature

#11 build(KL-99): check style 적용
  build.gradle
  src/main/java/taco/klkl/global/config/swagger/SwaggerConfig.java
  src/main/java/taco/klkl/global/error/ErrorResponse.java
  src/main/java/taco/klkl/global/error/exception/CustomException.java
  src/main/java/taco/klkl/global/response/GlobalResponseAdvice.java
  src/test/java/taco/klkl/global/error/GlobalExceptionHandlerTest.java
  src/test/java/taco/klkl/global/response/GlobalResponseAdviceTest.java
  tool/naver-checkstyle-rules.xml
  tool/naver-checkstyle-suppressions.xml
Labels: 💄 Style, 🛠️ Build

#12 feat(KL-66): create User API
  src/main/java/taco/klkl/domain/user/controller/UserController.java
  src/main/java/taco/klkl/domain/user/dao/UserRepository.java
  src/main/java/taco/klkl/domain/user/domain/User.java
  src/main/java/taco/klkl/domain/user/service/UserService.java
  src/main/java/taco/klkl/global/common/convert/GenderConvert.java
  src/main/java/taco/klkl/global/common/enums/Gender.java
  src/main/resources/application-h2.yaml
  src/test/java/taco/klkl/domain/user/Integration/UserIntegrationTest.java
  src/test/java/taco/klkl/domain/user/controller/UserControllerTest.java
  src/test/java/taco/klkl/domain/user/service/UserServiceTest.java
Labels: ✨ Feature

#13 chore(Kl-100): set up sql initialization
  src/main/java/taco/klkl/domain/user/controller/UserController.java
  src/main/resources/application-h2.yaml
  src/main/resources/database/data.sql
  src/test/java/taco/klkl/domain/user/Integration/UserIntegrationTest.java
  src/test/java/taco/klkl/domain/user/controller/UserControllerTest.java
Labels: ⚙️ Chore

#14 feat(KL-107): 상품 엔티티 구현
  src/main/java/taco/klkl/domain/product/domain/Product.java
  src/test/java/taco/klkl/domain/product/domain/ProductTest.java
Labels: ✅ Test, ✨ Feature

#15 feat(KL-109): 상품 repository 구현
  src/main/java/taco/klkl/domain/product/dao/ProductRepository.java
Labels: ✨ Feature

#17 feat(KL-112): create user dto
  src/main/java/taco/klkl/domain/user/controller/UserController.java
  src/main/java/taco/klkl/domain/user/domain/User.java
  src/main/java/taco/klkl/domain/user/dto/request/UserCreateRequestDto.java
  src/main/java/taco/klkl/domain/user/dto/response/UserDetailResponseDto.java
  src/main/java/taco/klkl/domain/user/dto/response/UserSimpleResponseDto.java
  src/main/java/taco/klkl/domain/user/service/UserService.java
  src/main/java/taco/klkl/global/common/enums/Gender.java
  src/test/java/taco/klkl/domain/user/controller/UserControllerTest.java
  src/test/java/taco/klkl/domain/user/dto/request/UserRequestDtoTest.java
  src/test/java/taco/klkl/domain/user/dto/response/UserDetailResponseDtoTest.java
  src/test/java/taco/klkl/domain/user/dto/response/UserSimpleResponseDtoTest.java
  src/test/java/taco/klkl/domain/user/integration/UserIntegrationTest.java
  src/test/java/taco/klkl/domain/user/service/UserServiceTest.java
Labels: ✨ Feature

#16 feat(KL-69): 카테고리 대분류 목록 조회 api 구현
  src/main/java/taco/klkl/domain/category/controller/CategoryController.java
  src/main/java/taco/klkl/domain/category/dao/CategoryRepository.java
  src/main/java/taco/klkl/domain/category/domain/Category.java
  src/main/java/taco/klkl/domain/category/dto/response/CategoryResponseDto.java
  src/main/java/taco/klkl/domain/category/service/CategoryService.java
  src/main/resources/database/data.sql
  src/test/java/taco/klkl/domain/category/controller/CategoryControllerTest.java
  src/test/java/taco/klkl/domain/category/integration/CategoryIntegrationTest.java
  src/test/java/taco/klkl/domain/category/service/CategoryServiceTest.java
Labels: ✨ Feature

#18 feat(KL-110) : create Product service
  src/main/java/taco/klkl/domain/product/domain/Product.java
  src/main/java/taco/klkl/domain/product/dto/request/ProductCreateRequestDto.java
  src/main/java/taco/klkl/domain/product/dto/request/ProductUpdateRequestDto.java
  src/main/java/taco/klkl/domain/product/dto/response/ProductDetailResponseDto.java
  src/main/java/taco/klkl/domain/product/dto/response/ProductSimpleResponseDto.java
  src/main/java/taco/klkl/domain/product/exception/ProductNotFoundException.java
  src/main/java/taco/klkl/domain/product/service/ProductService.java
  src/main/java/taco/klkl/global/common/constants/DefaultConstants.java
  src/main/java/taco/klkl/global/error/exception/ErrorCode.java
  src/main/java/taco/klkl/global/util/UserUtil.java
  src/test/java/taco/klkl/domain/product/domain/ProductTest.java
  src/test/java/taco/klkl/domain/product/dto/request/ProductCreateRequestDtoTest.java
  src/test/java/taco/klkl/domain/product/dto/request/ProductUpdateRequestDtoTest.java
  src/test/java/taco/klkl/domain/product/dto/response/ProductDetailResponseDtoTest.java
  src/test/java/taco/klkl/domain/product/dto/response/ProductSimpleResponseDtoTest.java
  src/test/java/taco/klkl/domain/product/service/ProductServiceTest.java
Labels: ✅ Test, ✨ Feature

#19 feat(KL-118): 지역 api 구현
  src/main/java/taco/klkl/domain/region/controller/RegionController.java
  src/main/java/taco/klkl/domain/region/dao/RegionRepository.java
  src/main/java/taco/klkl/domain/region/domain/Region.java
  src/main/java/taco/klkl/domain/region/dto/response/RegionResponseDto.java
  src/main/java/taco/klkl/domain/region/enums/RegionType.java
  src/main/java/taco/klkl/domain/region/enums/RegionTypeConvert.java
  src/main/java/taco/klkl/domain/region/exception/RegionNotFoundException.java
  src/main/java/taco/klkl/domain/region/service/RegionService.java
  src/main/java/taco/klkl/domain/region/service/RegionServiceImpl.java
  src/main/java/taco/klkl/global/error/exception/ErrorCode.java
  src/main/resources/application-h2.yaml
  src/main/resources/database/data.sql
  src/test/java/taco/klkl/domain/region/controller/RegionControllerTest.java
  src/test/java/taco/klkl/domain/region/integration/RegionIntegrationTest.java
  src/test/java/taco/klkl/domain/region/service/RegionServiceImplTest.java
Labels: ✨ Feature

#21 feat(KL-118): 지역 API 구현
  src/main/java/taco/klkl/domain/region/controller/RegionController.java
  src/main/java/taco/klkl/domain/region/dao/RegionRepository.java
  src/main/java/taco/klkl/domain/region/domain/Region.java
  src/main/java/taco/klkl/domain/region/dto/response/RegionResponseDto.java
  src/main/java/taco/klkl/domain/region/enums/RegionType.java
  src/main/java/taco/klkl/domain/region/enums/RegionTypeConvert.java
  src/main/java/taco/klkl/domain/region/exception/RegionNotFoundException.java
  src/main/java/taco/klkl/domain/region/service/RegionService.java
  src/main/java/taco/klkl/domain/region/service/RegionServiceImpl.java
  src/main/java/taco/klkl/global/error/exception/ErrorCode.java
  src/main/resources/application-h2.yaml
  src/main/resources/database/data.sql
  src/test/java/taco/klkl/domain/region/controller/RegionControllerTest.java
  src/test/java/taco/klkl/domain/region/integration/RegionIntegrationTest.java
  src/test/java/taco/klkl/domain/region/service/RegionServiceImplTest.java
Labels: ✨ Feature

#22 feat(KL-111): add Product controller
  src/main/java/taco/klkl/domain/product/controller/ProductController.java
  src/main/resources/database/data.sql
  src/test/java/taco/klkl/domain/product/controller/ProductControllerTest.java
  src/test/java/taco/klkl/domain/product/integration/ProductIntegrationTest.java
Labels: ✅ Test, ✨ Feature

#23 feat(KL-105): add Product integration API
  src/main/java/taco/klkl/domain/product/controller/ProductController.java
  src/main/java/taco/klkl/domain/product/dao/ProductRepository.java
  src/main/java/taco/klkl/domain/product/domain/Product.java
  src/main/java/taco/klkl/domain/product/dto/request/ProductCreateRequestDto.java
  src/main/java/taco/klkl/domain/product/dto/request/ProductUpdateRequestDto.java
  src/main/java/taco/klkl/domain/product/dto/response/ProductDetailResponseDto.java
  src/main/java/taco/klkl/domain/product/dto/response/ProductSimpleResponseDto.java
  src/main/java/taco/klkl/domain/product/exception/ProductNotFoundException.java
  src/main/java/taco/klkl/domain/product/service/ProductService.java
  src/main/java/taco/klkl/domain/user/domain/User.java
  src/main/java/taco/klkl/domain/user/service/UserService.java
  src/main/java/taco/klkl/global/common/constants/DefaultConstants.java
  src/main/java/taco/klkl/global/common/constants/ProductConstants.java
  src/main/java/taco/klkl/global/common/constants/UserConstants.java
  src/main/java/taco/klkl/global/error/exception/ErrorCode.java
  src/main/java/taco/klkl/global/util/UserUtil.java
  src/main/resources/database/data.sql
  src/test/java/taco/klkl/domain/product/controller/ProductControllerTest.java
  src/test/java/taco/klkl/domain/product/domain/ProductTest.java
  src/test/java/taco/klkl/domain/product/dto/request/ProductCreateRequestDtoTest.java
  src/test/java/taco/klkl/domain/product/dto/request/ProductUpdateRequestDtoTest.java
  src/test/java/taco/klkl/domain/product/dto/response/ProductDetailResponseDtoTest.java
  src/test/java/taco/klkl/domain/product/dto/response/ProductSimpleResponseDtoTest.java
  src/test/java/taco/klkl/domain/product/integration/ProductIntegrationTest.java
  src/test/java/taco/klkl/domain/product/service/ProductServiceTest.java
  src/test/java/taco/klkl/domain/user/controller/UserControllerTest.java
  src/test/java/taco/klkl/domain/user/dto/response/UserDetailResponseDtoTest.java
  src/test/java/taco/klkl/domain/user/service/UserServiceTest.java
Labels: ✅ Test, ✨ Feature

#26 refactor(KL-120): change category entity field to enum class
  src/main/java/taco/klkl/domain/category/controller/CategoryController.java
  src/main/java/taco/klkl/domain/category/convert/CategoryNameConverter.java
  src/main/java/taco/klkl/domain/category/domain/Category.java
  src/main/java/taco/klkl/domain/category/domain/CategoryName.java
  src/main/java/taco/klkl/domain/category/dto/response/CategoryResponseDto.java
  src/test/java/taco/klkl/domain/category/controller/CategoryControllerTest.java
  src/test/java/taco/klkl/domain/category/integration/CategoryIntegrationTest.java
  src/test/java/taco/klkl/domain/category/service/CategoryServiceTest.java
  src/test/java/taco/klkl/domain/subcategory/service/SubcategoryServiceTest.java
Labels: ♻️ Refactor
