Repository taco-official/klkl-server, pull requests merged in 2024-08, with the labels that each got.

#27 feat(KL-72): feat Region, Country API
  src/main/java/taco/klkl/domain/region/controller/CountryController.java
  src/main/java/taco/klkl/domain/region/controller/RegionController.java
  src/main/java/taco/klkl/domain/region/converter/CountryTypeConverter.java
  src/main/java/taco/klkl/domain/region/converter/RegionTypeConverter.java
  src/main/java/taco/klkl/domain/region/dao/CountryRepository.java
  src/main/java/taco/klkl/domain/region/dao/RegionRepository.java
  src/main/java/taco/klkl/domain/region/domain/Country.java
  src/main/java/taco/klkl/domain/region/domain/Region.java
  src/main/java/taco/klkl/domain/region/dto/response/CountryResponseDto.java
  src/main/java/taco/klkl/domain/region/dto/response/CountryWithOutRegionDto.java
  src/main/java/taco/klkl/domain/region/dto/response/RegionResponseDto.java
  src/main/java/taco/klkl/domain/region/dto/response/RegionSimpleResponseDto.java
  src/main/java/taco/klkl/domain/region/enums/CountryType.java
  src/main/java/taco/klkl/domain/region/enums/RegionType.java
  src/main/java/taco/klkl/domain/region/exception/CountryNotFoundException.java
  src/main/java/taco/klkl/domain/region/exception/RegionNotFoundException.java
  src/main/java/taco/klkl/domain/region/service/CountryService.java
  src/main/java/taco/klkl/domain/region/service/CountryServiceImpl.java
  src/main/java/taco/klkl/domain/region/service/RegionService.java
  src/main/java/taco/klkl/domain/region/service/RegionServiceImpl.java
  src/main/java/taco/klkl/global/error/exception/ErrorCode.java
  src/main/resources/application-h2.yaml
  src/main/resources/database/data.sql
  src/test/java/taco/klkl/domain/region/controller/CountryControllerTest.java
  src/test/java/taco/klkl/domain/region/controller/RegionControllerTest.java
  src/test/java/taco/klkl/domain/region/integration/CountryIntegrationTest.java
  src/test/java/taco/klkl/domain/region/integration/RegionIntegrationTest.java
  src/test/java/taco/klkl/domain/region/service/CountryServiceImplTest.java
  src/test/java/taco/klkl/domain/region/service/RegionServiceImplTest.java
Labels: ✅ Test, ✨ Feature

#25 feat(KL-68): update Product API
  src/main/java/taco/klkl/domain/product/controller/ProductController.java
  src/main/java/taco/klkl/domain/product/domain/Product.java
  src/main/java/taco/klkl/domain/product/dto/request/ProductCreateRequestDto.java
  src/main/java/taco/klkl/domain/product/dto/request/ProductUpdateRequestDto.java
  src/main/java/taco/klkl/domain/product/service/ProductService.java
  src/main/java/taco/klkl/global/common/constants/DefaultConstants.java
  src/main/java/taco/klkl/global/common/constants/ProductConstants.java
  src/main/java/taco/klkl/global/common/constants/ProductValidationMessages.java
  src/main/java/taco/klkl/global/common/constants/UserConstants.java
  src/main/java/taco/klkl/global/error/GlobalExceptionHandler.java
  src/main/java/taco/klkl/global/error/exception/ErrorCode.java
  src/main/resources/application-h2.yaml
  src/test/java/taco/klkl/domain/product/controller/ProductControllerTest.java
  src/test/java/taco/klkl/domain/product/domain/ProductTest.java
  src/test/java/taco/klkl/domain/product/dto/request/ProductCreateRequestDtoTest.java
  src/test/java/taco/klkl/domain/product/dto/request/ProductUpdateRequestDtoTest.java
  src/test/java/taco/klkl/domain/product/integration/ProductIntegrationTest.java
  src/test/java/taco/klkl/domain/product/service/ProductServiceTest.java
  src/test/java/taco/klkl/global/error/GlobalExceptionHandlerTest.java
Labels: ✅ Test, ✨ Feature

#29 feat(KL-70): delete Product API
  src/main/java/taco/klkl/domain/product/controller/ProductController.java
  src/main/java/taco/klkl/domain/product/domain/Product.java
  src/main/java/taco/klkl/domain/product/dto/request/ProductCreateRequestDto.java
  src/main/java/taco/klkl/domain/product/service/ProductService.java
  src/main/java/taco/klkl/global/common/constants/ProductConstants.java
  src/main/java/taco/klkl/global/common/constants/ProductValidationMessages.java
  src/test/java/taco/klkl/domain/product/controller/ProductControllerTest.java
  src/test/java/taco/klkl/domain/product/dto/request/ProductCreateRequestDtoTest.java
  src/test/java/taco/klkl/domain/product/service/ProductServiceTest.java
Labels: ✨ Feature

#30 feat(KL-72): create city, currency api
  Makefile
  application.log
  src/main/java/taco/klkl/domain/region/controller/CountryController.java
  src/main/java/taco/klkl/domain/region/controller/CurrencyController.java
  src/main/java/taco/klkl/domain/region/controller/RegionController.java
  src/main/java/taco/klkl/domain/region/converter/CityTypeConverter.java
  src/main/java/taco/klkl/domain/region/converter/CountryTypeConverter.java
  src/main/java/taco/klkl/domain/region/converter/CurrencyTypeConverter.java
  src/main/java/taco/klkl/domain/region/converter/RegionTypeConverter.java
  src/main/java/taco/klkl/domain/region/dao/CityRepository.java
  src/main/java/taco/klkl/domain/region/dao/CountryRepository.java
  src/main/java/taco/klkl/domain/region/dao/CurrencyRepository.java
  src/main/java/taco/klkl/domain/region/dao/RegionRepository.java
  src/main/java/taco/klkl/domain/region/domain/City.java
  src/main/java/taco/klkl/domain/region/domain/Country.java
  src/main/java/taco/klkl/domain/region/domain/Currency.java
  src/main/java/taco/klkl/domain/region/domain/Region.java
  src/main/java/taco/klkl/domain/region/dto/response/CityResponseDto.java
  src/main/java/taco/klkl/domain/region/dto/response/CountryResponseDto.java
  src/main/java/taco/klkl/domain/region/dto/response/CountryWithOutRegionDto.java
  src/main/java/taco/klkl/domain/region/dto/response/CurrencyResponseDto.java
  src/main/java/taco/klkl/domain/region/dto/response/RegionResponseDto.java
  src/main/java/taco/klkl/domain/region/dto/response/RegionSimpleResponseDto.java
  src/main/java/taco/klkl/domain/region/enums/CityType.java
  src/main/java/taco/klkl/domain/region/enums/CurrencyType.java
  src/main/java/taco/klkl/domain/region/exception/CityNotFoundException.java
  src/main/java/taco/klkl/domain/region/exception/CurrencyNotFoundException.java
  src/main/java/taco/klkl/domain/region/service/CityService.java
  src/main/java/taco/klkl/domain/region/service/CityServiceImpl.java
  src/main/java/taco/klkl/domain/region/service/CountryService.java
  src/main/java/taco/klkl/domain/region/service/CountryServiceImpl.java
  src/main/java/taco/klkl/domain/region/service/CurrencyService.java
  src/main/java/taco/klkl/domain/region/service/CurrencyServiceImpl.java
  src/main/java/taco/klkl/domain/region/service/RegionService.java
  src/main/java/taco/klkl/domain/region/service/RegionServiceImpl.java
  src/main/java/taco/klkl/global/error/exception/ErrorCode.java
  src/main/resources/application-h2.yaml
  src/main/resources/application.yaml
  src/main/resources/database/data.sql
  src/test/java/taco/klkl/domain/region/controller/CountryControllerTest.java
  src/test/java/taco/klkl/domain/region/controller/CurrencyControllerTest.java
  src/test/java/taco/klkl/domain/region/controller/RegionControllerTest.java
  src/test/java/taco/klkl/domain/region/integration/CountryIntegrationTest.java
  src/test/java/taco/klkl/domain/region/integration/RegionIntegrationTest.java
  src/test/java/taco/klkl/domain/region/service/CityServiceImplTest.java
  src/test/java/taco/klkl/domain/region/service/CountryServiceImplTest.java
  src/test/java/taco/klkl/domain/region/service/CurrencyServiceImplTest.java
  src/test/java/taco/klkl/domain/region/service/RegionServiceImplTest.java
Labels: ✅ Test, ✨ Feature

#31 feat(KL-125): get all products
  src/main/java/taco/klkl/domain/product/controller/ProductController.java
  src/main/java/taco/klkl/domain/product/service/ProductService.java
  src/main/java/taco/klkl/global/common/constants/ProductConstants.java
  src/test/java/taco/klkl/domain/product/controller/ProductControllerTest.java
  src/test/java/taco/klkl/domain/product/service/ProductServiceTest.java
Labels: ✨ Feature

#33 feat(KL-128): map other entities to Product
  src/main/java/taco/klkl/domain/category/service/SubcategoryService.java
  src/main/java/taco/klkl/domain/product/domain/Product.java
  src/main/java/taco/klkl/domain/product/dto/response/ProductDetailResponseDto.java
  src/main/java/taco/klkl/domain/product/dto/response/ProductSimpleResponseDto.java
  src/main/java/taco/klkl/domain/product/service/ProductService.java
  src/main/java/taco/klkl/domain/region/service/CityService.java
  src/main/java/taco/klkl/domain/region/service/CityServiceImpl.java
  src/main/java/taco/klkl/domain/region/service/CurrencyService.java
  src/main/java/taco/klkl/domain/region/service/CurrencyServiceImpl.java
  src/main/java/taco/klkl/global/common/constants/ProductConstants.java
  src/main/resources/database/data.sql
  src/test/java/taco/klkl/domain/product/controller/ProductControllerTest.java
  src/test/java/taco/klkl/domain/product/domain/ProductTest.java
  src/test/java/taco/klkl/domain/product/dto/response/ProductDetailResponseDtoTest.java
  src/test/java/taco/klkl/domain/product/dto/response/ProductSimpleResponseDtoTest.java
  src/test/java/taco/klkl/domain/product/integration/ProductIntegrationTest.java
  src/test/java/taco/klkl/domain/product/service/ProductServiceTest.java
  src/test/java/taco/klkl/domain/region/service/CityServiceImplTest.java
  src/test/java/taco/klkl/domain/region/service/CurrencyServiceImplTest.java
Labels: ✨ Feature

#34 refactor(KL-130): change Product update http method
  src/main/java/taco/klkl/domain/product/controller/ProductController.java
  src/main/java/taco/klkl/domain/product/domain/Product.java
  src/main/java/taco/klkl/domain/product/dto/request/ProductCreateUpdateRequestDto.java
  src/main/java/taco/klkl/domain/product/dto/request/ProductUpdateRequestDto.java
  src/main/java/taco/klkl/domain/product/dto/response/ProductDetailResponseDto.java
  src/main/java/taco/klkl/domain/product/dto/response/ProductSimpleResponseDto.java
  src/main/java/taco/klkl/domain/product/service/ProductService.java
  src/test/java/taco/klkl/domain/product/controller/ProductControllerTest.java
  src/test/java/taco/klkl/domain/product/domain/ProductTest.java
  src/test/java/taco/klkl/domain/product/dto/request/ProductCreateUpdateRequestDtoTest.java
  src/test/java/taco/klkl/domain/product/dto/request/ProductUpdateRequestDtoTest.java
  src/test/java/taco/klkl/domain/product/dto/response/ProductDetailResponseDtoTest.java
  src/test/java/taco/klkl/domain/product/dto/response/ProductSimpleResponseDtoTest.java
  src/test/java/taco/klkl/domain/product/integration/ProductIntegrationTest.java
  src/test/java/taco/klkl/domain/product/service/ProductServiceTest.java
Labels: ♻️ Refactor

#36 refactor(KL-132): change product detail response dto
  src/main/java/taco/klkl/domain/.gitkeep
  src/main/java/taco/klkl/domain/product/domain/Product.java
  src/main/java/taco/klkl/domain/product/dto/response/ProductDetailResponseDto.java
  src/main/java/taco/klkl/domain/product/service/ProductService.java
  src/main/java/taco/klkl/domain/user/converter/GenderConverter.java
  src/main/java/taco/klkl/domain/user/domain/Gender.java
  src/main/java/taco/klkl/domain/user/domain/User.java
  src/main/java/taco/klkl/domain/user/service/UserService.java
  src/main/java/taco/klkl/global/common/constants/UserConstants.java
  src/main/java/taco/klkl/global/common/response/GlobalResponse.java
  src/main/java/taco/klkl/global/common/response/GlobalResponseAdvice.java
  src/main/java/taco/klkl/global/error/GlobalExceptionHandler.java
  src/test/java/taco/klkl/domain/product/controller/ProductControllerTest.java
  src/test/java/taco/klkl/domain/product/domain/ProductTest.java
  src/test/java/taco/klkl/domain/product/dto/response/ProductDetailResponseDtoTest.java
  src/test/java/taco/klkl/domain/product/integration/ProductIntegrationTest.java
  src/test/java/taco/klkl/domain/product/service/ProductServiceTest.java
  src/test/java/taco/klkl/domain/user/dto/response/UserDetailResponseDtoTest.java
  src/test/java/taco/klkl/domain/user/dto/response/UserSimpleResponseDtoTest.java
  src/test/java/taco/klkl/domain/user/service/UserServiceTest.java
  src/test/java/taco/klkl/global/error/GlobalExceptionHandlerTest.java
  src/test/java/taco/klkl/global/response/GlobalResponseAdviceTest.java
Labels: ♻️ Refactor

#35 feat(KL-127): create Search API
  src/main/java/taco/klkl/domain/category/dao/CategoryRepository.java
  src/main/java/taco/klkl/domain/category/dao/SubcategoryRepository.java
  src/main/java/taco/klkl/domain/category/domain/CategoryName.java
  src/main/java/taco/klkl/domain/category/domain/SubcategoryName.java
  src/main/java/taco/klkl/domain/category/service/CategoryService.java
  src/main/java/taco/klkl/domain/category/service/SubcategoryService.java
  src/main/java/taco/klkl/domain/region/converter/CurrencyTypeConverter.java
  src/main/java/taco/klkl/domain/region/converter/RegionTypeConverter.java
  src/main/java/taco/klkl/domain/region/dao/CityRepository.java
  src/main/java/taco/klkl/domain/region/dao/CountryRepository.java
  src/main/java/taco/klkl/domain/region/domain/City.java
  src/main/java/taco/klkl/domain/region/domain/Country.java
  src/main/java/taco/klkl/domain/region/domain/Region.java
  src/main/java/taco/klkl/domain/region/dto/response/CityResponseDto.java
  src/main/java/taco/klkl/domain/region/dto/response/CountryResponseDto.java
  src/main/java/taco/klkl/domain/region/dto/response/CountrySimpleResponseDto.java
  src/main/java/taco/klkl/domain/region/dto/response/CurrencyResponseDto.java
  src/main/java/taco/klkl/domain/region/dto/response/RegionResponseDto.java
  src/main/java/taco/klkl/domain/region/enums/CityType.java
  src/main/java/taco/klkl/domain/region/enums/CountryType.java
  src/main/java/taco/klkl/domain/region/enums/CurrencyType.java
  src/main/java/taco/klkl/domain/region/enums/RegionType.java
  src/main/java/taco/klkl/domain/region/service/CityService.java
  src/main/java/taco/klkl/domain/region/service/CityServiceImpl.java
  src/main/java/taco/klkl/domain/region/service/CountryService.java
  src/main/java/taco/klkl/domain/region/service/CountryServiceImpl.java
  src/main/java/taco/klkl/domain/region/service/RegionServiceImpl.java
  src/main/java/taco/klkl/domain/search/controller/SearchController.java
  src/main/java/taco/klkl/domain/search/dto/response/SearchResponseDto.java
  src/main/java/taco/klkl/domain/search/service/SearchService.java
  src/main/java/taco/klkl/domain/search/service/SearchServiceImpl.java
  src/main/java/taco/klkl/global/error/GlobalExceptionHandler.java
  src/main/java/taco/klkl/global/error/exception/ErrorCode.java
  src/test/java/taco/klkl/domain/category/domain/CategoryNameTest.java
  src/test/java/taco/klkl/domain/category/domain/SubcategoryNameTest.java
  src/test/java/taco/klkl/domain/category/service/CategoryServiceTest.java
  src/test/java/taco/klkl/domain/category/service/SubcategoryServiceTest.java
  src/test/java/taco/klkl/domain/region/enums/CityTypeTest.java
  src/test/java/taco/klkl/domain/region/enums/CountryTypeTest.java
  src/test/java/taco/klkl/domain/region/service/CityServiceImplTest.java
  src/test/java/taco/klkl/domain/region/service/CountryServiceImplTest.java
  src/test/java/taco/klkl/domain/search/controller/SearchControllerTest.java
  src/test/java/taco/klkl/domain/search/integration/SearchIntegrationTest.java
  src/test/java/taco/klkl/domain/search/service/SearchServiceImplTest.java
Labels: ✅ Test, ✨ Feature

#39 feat(KL-121) : create comment API
  src/main/java/taco/klkl/domain/comment/controller/CommentController.java
  src/main/java/taco/klkl/domain/comment/dao/CommentRepository.java
  src/main/java/taco/klkl/domain/comment/domain/Comment.java
  src/main/java/taco/klkl/domain/comment/dto/request/CommentCreateUpdateRequestDto.java
  src/main/java/taco/klkl/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/taco/klkl/domain/comment/exception/CommentNotFoundException.java
  src/main/java/taco/klkl/domain/comment/exception/CommentProductNotMatch.java
  src/main/java/taco/klkl/domain/comment/service/CommentService.java
  src/main/java/taco/klkl/domain/product/service/ProductService.java
  src/main/java/taco/klkl/global/common/constants/CommentValidationMessages.java
  src/main/java/taco/klkl/global/error/exception/ErrorCode.java
  src/main/resources/database/data.sql
  src/test/java/taco/klkl/domain/comment/controller/CommentControllerTest.java
  src/test/java/taco/klkl/domain/comment/dto/request/CommentCreateUpdateRequestDtoTest.java
  src/test/java/taco/klkl/domain/comment/integration/CommentIntegrationTest.java
  src/test/java/taco/klkl/domain/comment/service/CommentServiceTest.java
Labels: ✅ Test, ✨ Feature

#40 feat(KL-90): filter products by cities
  src/main/java/taco/klkl/domain/category/service/SubcategoryService.java
  src/main/java/taco/klkl/domain/product/controller/ProductController.java
  src/main/java/taco/klkl/domain/product/dto/request/ProductFilterOptionsDto.java
  src/main/java/taco/klkl/domain/product/exception/InvalidCityIdsException.java
  src/main/java/taco/klkl/domain/product/service/ProductService.java
  src/main/java/taco/klkl/domain/region/service/CityService.java
  src/main/java/taco/klkl/domain/region/service/CityServiceImpl.java
  src/main/java/taco/klkl/domain/region/service/CountryService.java
  src/main/java/taco/klkl/domain/region/service/CountryServiceImpl.java
  src/main/java/taco/klkl/domain/region/service/CurrencyService.java
  src/main/java/taco/klkl/domain/region/service/CurrencyServiceImpl.java
  src/main/java/taco/klkl/global/error/exception/ErrorCode.java
  src/test/java/taco/klkl/domain/product/controller/ProductControllerTest.java
  src/test/java/taco/klkl/domain/product/integration/ProductIntegrationTest.java
  src/test/java/taco/klkl/domain/product/service/ProductServiceTest.java
  src/test/java/taco/klkl/domain/region/service/CityServiceImplTest.java
Labels: ✨ Feature

#41 feat(KL-71): filter products by country & city
  build.gradle
  src/main/java/taco/klkl/domain/.gitkeep
  src/main/java/taco/klkl/domain/category/service/SubcategoryService.java
  src/main/java/taco/klkl/domain/comment/controller/CommentController.java
  src/main/java/taco/klkl/domain/comment/dao/CommentRepository.java
  src/main/java/taco/klkl/domain/comment/service/CommentService.java
  src/main/java/taco/klkl/domain/product/controller/ProductController.java
  src/main/java/taco/klkl/domain/product/domain/Product.java
  src/main/java/taco/klkl/domain/product/dto/request/ProductCreateUpdateRequestDto.java
  src/main/java/taco/klkl/domain/product/dto/request/ProductFilterOptionsDto.java
  src/main/java/taco/klkl/domain/product/dto/request/ProductUpdateRequestDto.java
  src/main/java/taco/klkl/domain/product/dto/response/ProductDetailResponseDto.java
  src/main/java/taco/klkl/domain/product/dto/response/ProductSimpleResponseDto.java
  src/main/java/taco/klkl/domain/product/exception/InvalidCityIdsException.java
  src/main/java/taco/klkl/domain/product/service/ProductService.java
  src/main/java/taco/klkl/domain/region/service/CityService.java
  src/main/java/taco/klkl/domain/region/service/CityServiceImpl.java
  src/main/java/taco/klkl/domain/region/service/CountryService.java
  src/main/java/taco/klkl/domain/region/service/CountryServiceImpl.java
  src/main/java/taco/klkl/domain/region/service/CurrencyService.java
  src/main/java/taco/klkl/domain/region/service/CurrencyServiceImpl.java
  src/main/java/taco/klkl/domain/user/converter/GenderConverter.java
  src/main/java/taco/klkl/domain/user/domain/Gender.java
  src/main/java/taco/klkl/domain/user/domain/User.java
  src/main/java/taco/klkl/domain/user/service/UserService.java
  src/main/java/taco/klkl/global/common/constants/CommentValidationMessages.java
  src/main/java/taco/klkl/global/common/constants/ProductConstants.java
  src/main/java/taco/klkl/global/common/constants/UserConstants.java
  src/main/java/taco/klkl/global/common/response/GlobalResponse.java
  src/main/java/taco/klkl/global/common/response/GlobalResponseAdvice.java
  src/main/java/taco/klkl/global/common/response/PagedResponseDto.java
  src/main/java/taco/klkl/global/config/querydsl/QueryDslConfig.java
  src/main/java/taco/klkl/global/error/GlobalExceptionHandler.java
  src/main/java/taco/klkl/global/error/exception/ErrorCode.java
  src/main/resources/database/data.sql
  src/test/java/taco/klkl/domain/comment/controller/CommentControllerTest.java
  src/test/java/taco/klkl/domain/comment/integration/CommentIntegrationTest.java
  src/test/java/taco/klkl/domain/comment/service/CommentServiceTest.java
  src/test/java/taco/klkl/domain/product/controller/ProductControllerTest.java
  src/test/java/taco/klkl/domain/product/domain/ProductTest.java
  src/test/java/taco/klkl/domain/product/dto/request/ProductCreateUpdateRequestDtoTest.java
  src/test/java/taco/klkl/domain/product/dto/request/ProductUpdateRequestDtoTest.java
  src/test/java/taco/klkl/domain/product/dto/response/ProductDetailResponseDtoTest.java
  src/test/java/taco/klkl/domain/product/dto/response/ProductSimpleResponseDtoTest.java
  src/test/java/taco/klkl/domain/product/integration/ProductIntegrationTest.java
  src/test/java/taco/klkl/domain/product/service/ProductServiceTest.java
  src/test/java/taco/klkl/domain/region/service/CityServiceImplTest.java
  src/test/java/taco/klkl/domain/region/service/CurrencyServiceImplTest.java
  src/test/java/taco/klkl/domain/user/dto/response/UserDetailResponseDtoTest.java
  src/test/java/taco/klkl/domain/user/dto/response/UserSimpleResponseDtoTest.java
  src/test/java/taco/klkl/domain/user/service/UserServiceTest.java
  src/test/java/taco/klkl/global/error/GlobalExceptionHandlerTest.java
  src/test/java/taco/klkl/global/response/GlobalResponseAdviceTest.java
Labels: ✨ Feature

#42 feat(KL-92): filter products by subcategory ids
  src/main/java/taco/klkl/domain/product/controller/ProductController.java
  src/main/java/taco/klkl/domain/product/dto/request/ProductFilterOptionsDto.java
  src/main/java/taco/klkl/domain/product/service/ProductService.java
  src/main/java/taco/klkl/domain/region/service/CityService.java
  src/main/java/taco/klkl/domain/region/service/CityServiceImpl.java
  src/main/resources/database/data.sql
  src/test/java/taco/klkl/domain/product/integration/ProductIntegrationTest.java
  src/test/java/taco/klkl/domain/product/service/ProductServiceTest.java
Labels: ✨ Feature

#38 feat(KL-133): create product like API
  src/main/java/taco/klkl/domain/like/controller/LikeController.java
  src/main/java/taco/klkl/domain/like/dao/LikeRepository.java
  src/main/java/taco/klkl/domain/like/domain/Like.java
  src/main/java/taco/klkl/domain/like/dto/response/LikeResponseDto.java
  src/main/java/taco/klkl/domain/like/exception/LikeCountBelowMinimumException.java
  src/main/java/taco/klkl/domain/like/exception/LikeCountOverMaximumException.java
  src/main/java/taco/klkl/domain/like/service/LikeService.java
  src/main/java/taco/klkl/domain/like/service/LikeServiceImpl.java
  src/main/java/taco/klkl/domain/product/domain/Product.java
  src/main/java/taco/klkl/domain/product/service/ProductService.java
  src/main/java/taco/klkl/global/error/exception/ErrorCode.java
  src/main/java/taco/klkl/global/util/UserUtil.java
  src/test/java/taco/klkl/domain/like/controller/LikeControllerTest.java
  src/test/java/taco/klkl/domain/like/integration/LikeIntegrationTest.java
  src/test/java/taco/klkl/domain/like/service/LikeServiceImplTest.java
  src/test/java/taco/klkl/domain/product/domain/ProductTest.java
  src/test/java/taco/klkl/domain/product/service/ProductServiceTest.java
Labels: ✅ Test, ✨ Feature

#46 feat(KL-144): feat cors config class
  src/main/java/taco/klkl/global/config/web/WebConfig.java
  src/test/java/taco/klkl/global/config/web/WebConfigTest.java
Labels: ✅ Test, ✨ Feature

#43 feat(KL-140): add product search
  src/main/java/taco/klkl/domain/product/service/ProductService.java
  src/main/java/taco/klkl/domain/search/dto/response/SearchResponseDto.java
  src/main/java/taco/klkl/domain/search/service/SearchServiceImpl.java
  src/test/java/taco/klkl/domain/product/service/ProductServiceTest.java
  src/test/java/taco/klkl/domain/search/controller/SearchControllerTest.java
  src/test/java/taco/klkl/domain/search/integration/SearchIntegrationTest.java
  src/test/java/taco/klkl/domain/search/service/SearchServiceImplTest.java
Labels: ✅ Test, ✨ Feature

#44 feat(KL-93): filter products by filterIds
  src/main/java/taco/klkl/domain/category/dao/FilterRepository.java
  src/main/java/taco/klkl/domain/category/domain/Filter.java
  src/main/java/taco/klkl/domain/category/dto/response/FilterResponseDto.java
  src/main/java/taco/klkl/domain/category/exception/FilterNotFoundException.java
  src/main/java/taco/klkl/domain/category/service/FilterService.java
  src/main/java/taco/klkl/domain/comment/service/CommentService.java
  src/main/java/taco/klkl/domain/product/controller/ProductController.java
  src/main/java/taco/klkl/domain/product/dao/ProductFilterRepository.java
  src/main/java/taco/klkl/domain/product/domain/Product.java
  src/main/java/taco/klkl/domain/product/domain/ProductFilter.java
  src/main/java/taco/klkl/domain/product/dto/request/ProductCreateUpdateRequestDto.java
  src/main/java/taco/klkl/domain/product/dto/request/ProductFilterOptionsDto.java
  src/main/java/taco/klkl/domain/product/dto/response/ProductDetailResponseDto.java
  src/main/java/taco/klkl/domain/product/dto/response/ProductSimpleResponseDto.java
  src/main/java/taco/klkl/domain/product/service/ProductService.java
  src/main/java/taco/klkl/domain/region/service/CityService.java
  src/main/java/taco/klkl/domain/region/service/CityServiceImpl.java
  src/main/java/taco/klkl/global/error/exception/ErrorCode.java
  src/main/java/taco/klkl/global/util/ProductUtil.java
  src/test/java/taco/klkl/domain/category/controller/FilterControllerTest.java
  src/test/java/taco/klkl/domain/category/service/FilterServiceTest.java
  src/test/java/taco/klkl/domain/category/service/SubcategoryFilterServiceTest.java
  src/test/java/taco/klkl/domain/comment/service/CommentServiceTest.java
  src/test/java/taco/klkl/domain/product/controller/ProductControllerTest.java
  src/test/java/taco/klkl/domain/product/dto/request/ProductCreateUpdateRequestDtoTest.java
  src/test/java/taco/klkl/domain/product/dto/response/ProductDetailResponseDtoTest.java
  src/test/java/taco/klkl/domain/product/dto/response/ProductSimpleResponseDtoTest.java
  src/test/java/taco/klkl/domain/product/integration/ProductIntegrationTest.java
  src/test/java/taco/klkl/domain/product/service/ProductServiceTest.java
Labels: ✨ Feature

#47 feat(KL-131): add rating field to product
  src/main/java/taco/klkl/domain/product/converter/RatingConverter.java
  src/main/java/taco/klkl/domain/product/domain/Product.java
  src/main/java/taco/klkl/domain/product/domain/Rating.java
  src/main/java/taco/klkl/domain/product/dto/request/ProductCreateUpdateRequestDto.java
  src/main/java/taco/klkl/domain/product/dto/response/ProductDetailResponseDto.java
  src/main/java/taco/klkl/domain/product/dto/response/ProductSimpleResponseDto.java
  src/main/java/taco/klkl/domain/product/exception/RatingNotFoundException.java
  src/main/java/taco/klkl/domain/product/service/ProductService.java
  src/main/java/taco/klkl/global/common/constants/ProductConstants.java
  src/main/java/taco/klkl/global/common/constants/ProductValidationMessages.java
  src/main/java/taco/klkl/global/error/exception/ErrorCode.java
  src/main/resources/database/data.sql
  src/test/java/taco/klkl/domain/comment/controller/CommentControllerTest.java
  src/test/java/taco/klkl/domain/product/controller/ProductControllerTest.java
  src/test/java/taco/klkl/domain/product/domain/ProductTest.java
  src/test/java/taco/klkl/domain/product/dto/request/ProductCreateUpdateRequestDtoTest.java
  src/test/java/taco/klkl/domain/product/dto/response/ProductDetailResponseDtoTest.java
  src/test/java/taco/klkl/domain/product/dto/response/ProductSimpleResponseDtoTest.java
  src/test/java/taco/klkl/domain/product/integration/ProductIntegrationTest.java
  src/test/java/taco/klkl/domain/product/service/ProductServiceTest.java
Labels: ✨ Feature

#45 feat(KL-134): add notification API
  src/main/java/taco/klkl/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/taco/klkl/domain/comment/service/CommentService.java
  src/main/java/taco/klkl/domain/notification/controller/NotificationController.java
  src/main/java/taco/klkl/domain/notification/dao/NotificationRepository.java
  src/main/java/taco/klkl/domain/notification/domain/Notification.java
  src/main/java/taco/klkl/domain/notification/dto/response/NotificationInfo.java
  src/main/java/taco/klkl/domain/notification/dto/response/NotificationResponse.java
  src/main/java/taco/klkl/domain/notification/exception/NotificationNotFoundException.java
  src/main/java/taco/klkl/domain/notification/service/NotificationService.java
  src/main/java/taco/klkl/domain/notification/service/NotificationServiceImpl.java
  src/main/java/taco/klkl/global/common/constants/NotificationConstants.java
  src/main/java/taco/klkl/global/error/exception/ErrorCode.java
  src/main/resources/database/data.sql
  src/test/java/taco/klkl/domain/comment/controller/CommentControllerTest.java
  src/test/java/taco/klkl/domain/comment/service/CommentServiceTest.java
  src/test/java/taco/klkl/domain/notification/controller/NotificationControllerTest.java
  src/test/java/taco/klkl/domain/notification/integration/NotificationIntegrationTest.java
  src/test/java/taco/klkl/domain/notification/service/NotificationServiceTest.java
Labels: ✅ Test, ✨ Feature

#48 feat(KL-94): sort products
  src/main/java/taco/klkl/domain/product/controller/ProductController.java
  src/main/java/taco/klkl/domain/product/dto/request/ProductSortOptionsDto.java
  src/main/java/taco/klkl/domain/product/exception/InvalidSortOptionException.java
  src/main/java/taco/klkl/domain/product/service/ProductService.java
  src/main/java/taco/klkl/global/common/constants/ProductConstants.java
  src/main/java/taco/klkl/global/error/exception/ErrorCode.java
  src/main/resources/database/data.sql
  src/test/java/taco/klkl/domain/product/controller/ProductControllerTest.java
  src/test/java/taco/klkl/domain/product/integration/ProductIntegrationTest.java
  src/test/java/taco/klkl/domain/product/service/ProductServiceTest.java
Labels: ✨ Feature

#49 feat(KL-71): get product list with filtering and sorting
  src/main/java/taco/klkl/domain/category/dao/FilterRepository.java
  src/main/java/taco/klkl/domain/category/domain/Filter.java
  src/main/java/taco/klkl/domain/category/dto/response/FilterResponseDto.java
  src/main/java/taco/klkl/domain/category/exception/FilterNotFoundException.java
  src/main/java/taco/klkl/domain/category/service/FilterService.java
  src/main/java/taco/klkl/domain/comment/service/CommentService.java
  src/main/java/taco/klkl/domain/like/service/LikeServiceImpl.java
  src/main/java/taco/klkl/domain/product/controller/ProductController.java
  src/main/java/taco/klkl/domain/product/converter/RatingConverter.java
  src/main/java/taco/klkl/domain/product/dao/ProductFilterRepository.java
  src/main/java/taco/klkl/domain/product/domain/Product.java
  src/main/java/taco/klkl/domain/product/domain/ProductFilter.java
  src/main/java/taco/klkl/domain/product/domain/Rating.java
  src/main/java/taco/klkl/domain/product/dto/request/ProductCreateUpdateRequestDto.java
  src/main/java/taco/klkl/domain/product/dto/request/ProductFilterOptionsDto.java
  src/main/java/taco/klkl/domain/product/dto/request/ProductSortOptionsDto.java
  src/main/java/taco/klkl/domain/product/dto/response/ProductDetailResponseDto.java
  src/main/java/taco/klkl/domain/product/dto/response/ProductSimpleResponseDto.java
  src/main/java/taco/klkl/domain/product/exception/InvalidSortOptionException.java
  src/main/java/taco/klkl/domain/product/exception/RatingNotFoundException.java
  src/main/java/taco/klkl/domain/product/service/ProductService.java
  src/main/java/taco/klkl/domain/region/service/CityService.java
  src/main/java/taco/klkl/domain/region/service/CityServiceImpl.java
  src/main/java/taco/klkl/global/common/constants/ProductConstants.java
  src/main/java/taco/klkl/global/common/constants/ProductValidationMessages.java
  src/main/java/taco/klkl/global/error/exception/ErrorCode.java
  src/main/java/taco/klkl/global/util/ProductUtil.java
  src/main/resources/database/data.sql
  src/test/java/taco/klkl/domain/category/controller/FilterControllerTest.java
  src/test/java/taco/klkl/domain/category/service/FilterServiceTest.java
  src/test/java/taco/klkl/domain/category/service/SubcategoryFilterServiceTest.java
  src/test/java/taco/klkl/domain/comment/controller/CommentControllerTest.java
  src/test/java/taco/klkl/domain/comment/service/CommentServiceTest.java
  src/test/java/taco/klkl/domain/like/integration/LikeIntegrationTest.java
  src/test/java/taco/klkl/domain/like/service/LikeServiceImplTest.java
  src/test/java/taco/klkl/domain/notification/controller/NotificationControllerTest.java
  src/test/java/taco/klkl/domain/notification/service/NotificationServiceTest.java
  src/test/java/taco/klkl/domain/product/controller/ProductControllerTest.java
  src/test/java/taco/klkl/domain/product/domain/ProductTest.java
  src/test/java/taco/klkl/domain/product/dto/request/ProductCreateUpdateRequestDtoTest.java
  src/test/java/taco/klkl/domain/product/dto/response/ProductDetailResponseDtoTest.java
  src/test/java/taco/klkl/domain/product/dto/response/ProductSimpleResponseDtoTest.java
  src/test/java/taco/klkl/domain/product/integration/ProductIntegrationTest.java
  src/test/java/taco/klkl/domain/product/service/ProductServiceTest.java
  src/test/java/taco/klkl/domain/search/controller/SearchControllerTest.java
  src/test/java/taco/klkl/domain/search/service/SearchServiceImplTest.java
Labels: ✨ Feature

#50 feat(KL-148): add city data
  src/main/java/taco/klkl/domain/region/enums/CityType.java
  src/main/resources/database/data.sql
Labels: ✨ Feature

#52 feat(KL-150): add mysql option
  .github/workflows/makefile.yaml
  .gitignore
  application.log
  build.gradle
  compose.yaml
  src/main/java/taco/klkl/domain/category/domain/Category.java
  src/main/java/taco/klkl/domain/category/domain/Subcategory.java
  src/main/java/taco/klkl/domain/category/domain/SubcategoryTag.java
  src/main/java/taco/klkl/domain/category/domain/Tag.java
  src/main/java/taco/klkl/domain/comment/domain/Comment.java
  src/main/java/taco/klkl/domain/notification/domain/Notification.java
  src/main/java/taco/klkl/domain/product/domain/ProductTag.java
  src/main/java/taco/klkl/domain/region/domain/City.java
  src/main/java/taco/klkl/domain/region/domain/Country.java
  src/main/java/taco/klkl/domain/region/domain/Currency.java
  src/main/java/taco/klkl/domain/region/domain/Region.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-h2.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application-mysql.yaml
  src/main/resources/application-swagger.yaml
  src/main/resources/application.yaml
  src/main/resources/database/data.sql
Labels: ⚙️ Chore, ✨ Feature

#53 fix(KL-152): fix search product api, some test
  src/main/java/taco/klkl/domain/product/controller/ProductController.java
  src/main/java/taco/klkl/domain/product/service/ProductService.java
  src/main/java/taco/klkl/domain/product/service/ProductServiceImpl.java
  src/main/java/taco/klkl/domain/region/domain/CurrencyType.java
  src/main/java/taco/klkl/domain/search/dto/response/SearchResponse.java
  src/main/java/taco/klkl/domain/search/service/SearchServiceImpl.java
  src/main/java/taco/klkl/global/config/web/WebConfig.java
  src/main/resources/database/data.sql
  src/test/java/taco/klkl/domain/product/controller/ProductControllerTest.java
  src/test/java/taco/klkl/domain/product/integration/ProductIntegrationTest.java
  src/test/java/taco/klkl/domain/product/service/ProductServiceImplTest.java
  src/test/java/taco/klkl/domain/search/controller/SearchControllerTest.java
  src/test/java/taco/klkl/domain/search/integration/SearchIntegrationTest.java
  src/test/java/taco/klkl/domain/search/service/SearchServiceImplTest.java
  src/test/java/taco/klkl/global/config/web/WebConfigTest.java
Labels: ⚙️ Chore, ✅ Test

#54 fix(KL-153): change tag response structure
  src/main/java/taco/klkl/domain/category/controller/TagController.java
  src/main/java/taco/klkl/domain/category/dao/SubcategoryTagRepository.java
  src/main/java/taco/klkl/domain/category/dto/response/SubcategoryWithTagsResponse.java
  src/main/java/taco/klkl/domain/category/service/SubcategoryTagService.java
  src/main/java/taco/klkl/domain/category/service/SubcategoryTagServiceImpl.java
  src/test/java/taco/klkl/domain/category/controller/TagControllerTest.java
  src/test/java/taco/klkl/domain/category/integration/TagIntegrationTest.java
  src/test/java/taco/klkl/domain/category/service/SubcategoryTagServiceImplTest.java
Labels: ♻️ Refactor

#56 feat(KL-157): add Location header
  src/main/java/taco/klkl/domain/product/controller/ProductController.java
  src/main/java/taco/klkl/domain/product/service/ProductServiceImpl.java
  src/test/java/taco/klkl/domain/product/controller/ProductControllerTest.java
  src/test/java/taco/klkl/domain/product/integration/ProductIntegrationTest.java
Labels: ✨ Feature

#57 feat(KL-156): change category response dto and add comment cascade
  src/main/java/taco/klkl/domain/category/dto/response/CategoryResponse.java
  src/main/java/taco/klkl/domain/comment/domain/Comment.java
  src/main/java/taco/klkl/domain/product/domain/Product.java
  src/test/java/taco/klkl/domain/category/controller/CategoryControllerTest.java
  src/test/java/taco/klkl/domain/category/integration/CategoryIntegrationTest.java
  src/test/java/taco/klkl/domain/category/service/CategoryServiceImplTest.java
Labels: ♻️ Refactor

#58 feat(KL-155): create kakao oauth2
  src/main/java/taco/klkl/domain/oauth/controller/OauthKakaoController.java
  src/main/java/taco/klkl/domain/oauth/dao/OauthRepository.java
  src/main/java/taco/klkl/domain/oauth/domain/Oauth.java
  src/main/java/taco/klkl/domain/oauth/dto/request/KakaoUserInfoRequest.java
  src/main/java/taco/klkl/domain/oauth/service/OauthKakaoLoginService.java
  src/main/java/taco/klkl/domain/oauth/service/OauthKakaoLoginServiceImpl.java
  src/main/java/taco/klkl/domain/oauth/service/OauthKakaoService.java
  src/main/java/taco/klkl/domain/oauth/service/OauthKakaoServiceImpl.java
  src/main/java/taco/klkl/domain/user/converter/GenderConverter.java
  src/main/java/taco/klkl/domain/user/dao/UserRepository.java
  src/main/java/taco/klkl/domain/user/dto/request/UserCreateRequest.java
  src/main/java/taco/klkl/domain/user/exception/UserNotFoundException.java
  src/main/java/taco/klkl/domain/user/service/UserService.java
  src/main/java/taco/klkl/global/common/constants/UserConstants.java
  src/main/java/taco/klkl/global/error/GlobalExceptionHandler.java
  src/main/java/taco/klkl/global/error/exception/ErrorCode.java
  src/main/java/taco/klkl/global/util/StringUtil.java
  src/main/java/taco/klkl/global/util/UserUtil.java
  src/main/resources/application-oauth.yaml
  src/main/resources/application.yaml
  src/test/java/taco/klkl/domain/user/service/UserServiceTest.java
Labels: ✨ Feature

#59 feat(KL-119): add s3 image
  .github/workflows/makefile.yaml
  build.gradle
  src/main/java/taco/klkl/domain/category/controller/TagController.java
  src/main/java/taco/klkl/domain/image/controller/ImageController.java
  src/main/java/taco/klkl/domain/image/dao/ImageRepository.java
  src/main/java/taco/klkl/domain/image/domain/FileExtension.java
  src/main/java/taco/klkl/domain/image/domain/Image.java
  src/main/java/taco/klkl/domain/image/domain/ImageType.java
  src/main/java/taco/klkl/domain/image/domain/UploadState.java
  src/main/java/taco/klkl/domain/image/dto/request/ImageUploadRequest.java
  src/main/java/taco/klkl/domain/image/dto/response/PresignedUrlResponse.java
  src/main/java/taco/klkl/domain/image/exception/FileExtensionNotFoundException.java
  src/main/java/taco/klkl/domain/image/exception/ImageNotFoundException.java
  src/main/java/taco/klkl/domain/image/exception/ImageTypeNotFoundException.java
  src/main/java/taco/klkl/domain/image/exception/ImageUploadNotCompleteException.java
  src/main/java/taco/klkl/domain/image/exception/ImageUrlInvalidException.java
  src/main/java/taco/klkl/domain/image/exception/UploadStateNotFoundException.java
  src/main/java/taco/klkl/domain/image/service/ImageKeyGenerator.java
  src/main/java/taco/klkl/domain/image/service/ImageService.java
  src/main/java/taco/klkl/domain/image/service/ImageServiceImpl.java
  src/main/java/taco/klkl/domain/oauth/service/OauthKakaoLoginServiceImpl.java
  src/main/java/taco/klkl/domain/product/domain/Product.java
  src/main/java/taco/klkl/domain/product/domain/ProductImage.java
  src/main/java/taco/klkl/domain/product/dto/response/ProductDetailResponse.java
  src/main/java/taco/klkl/domain/product/dto/response/ProductImageResponse.java
  src/main/java/taco/klkl/domain/product/dto/response/ProductSimpleResponse.java
  src/main/java/taco/klkl/domain/product/service/ProductServiceImpl.java
  src/main/java/taco/klkl/domain/search/controller/SearchController.java
  src/main/java/taco/klkl/domain/user/controller/UserController.java
  src/main/java/taco/klkl/domain/user/converter/GenderConverter.java
  src/main/java/taco/klkl/domain/user/domain/Gender.java
  src/main/java/taco/klkl/domain/user/domain/User.java
  src/main/java/taco/klkl/domain/user/dto/request/UserCreateRequest.java
  src/main/java/taco/klkl/domain/user/dto/request/UserUpdateRequest.java
  src/main/java/taco/klkl/domain/user/dto/response/UserDetailResponse.java
  src/main/java/taco/klkl/domain/user/dto/response/UserSimpleResponse.java
  src/main/java/taco/klkl/domain/user/exception/GenderNotFoundException.java
  src/main/java/taco/klkl/domain/user/service/UserService.java
  src/main/java/taco/klkl/domain/user/service/UserServiceImpl.java
  src/main/java/taco/klkl/global/common/constants/ImageValidationMessages.java
  src/main/java/taco/klkl/global/common/constants/NotificationConstants.java
  src/main/java/taco/klkl/global/common/constants/UserConstants.java
  src/main/java/taco/klkl/global/config/s3/S3Config.java
  src/main/java/taco/klkl/global/error/exception/ErrorCode.java
  src/main/java/taco/klkl/global/util/UserUtil.java
  src/main/resources/application-storage.yaml
  src/main/resources/application.yaml
  src/main/resources/database/data.sql
  src/test/java/taco/klkl/domain/comment/controller/CommentControllerTest.java
  src/test/java/taco/klkl/domain/comment/service/CommentServiceTest.java
  src/test/java/taco/klkl/domain/notification/service/NotificationServiceTest.java
  src/test/java/taco/klkl/domain/product/controller/ProductControllerTest.java
  src/test/java/taco/klkl/domain/product/dto/response/ProductSimpleResponseTest.java
  src/test/java/taco/klkl/domain/user/controller/UserControllerTest.java
  src/test/java/taco/klkl/domain/user/dto/request/UserRequestDtoTest.java
  src/test/java/taco/klkl/domain/user/dto/response/UserDetailResponseTest.java
  src/test/java/taco/klkl/domain/user/dto/response/UserSimpleResponseTest.java
  src/test/java/taco/klkl/domain/user/integration/UserIntegrationTest.java
  src/test/java/taco/klkl/domain/user/service/UserServiceImplTest.java
  src/test/resources/application-test.yaml
Labels: ✨ Feature
